'use client'

import ExcelJS from 'exceljs'
import {saveAs} from 'file-saver'
import {
  buildLatestPendingReasonMap,
  fetchTaskStatusHistory,
  type TaskStatusHistoryEntry,
} from '@/lib/tasks/taskStatusHistory'
import {getCategoryKey, getPriorityKey, getStatusKey} from '@/lib/tasks/taskLabels'
import type {EditableTask} from '@/lib/tasks/taskTypes'

type ExportableTask = EditableTask & {
  created_at?: string | null
}

type TranslateFn = (
  key: string,
  values?: Record<string, string | number | Date>
) => string

type ExportTasksToExcelParams = {
  tasks: ExportableTask[]
  buildingName: string
  locale: string
  t: TranslateFn
}

const COLORS = {
  green: '145C43',
  greenDark: '0F4A35',
  greenLight: 'EAF4EE',
  blue: '2F66C8',
  blueLight: 'EEF4FF',
  red: 'D64555',
  redLight: 'FFF1F3',
  amber: 'E88A00',
  amberLight: 'FFF7E6',
  text: '142952',
  border: 'D9E2EC',
  white: 'FFFFFF',
}

function safeT(
  t: TranslateFn,
  key: string,
  fallback: string,
  values?: Record<string, string | number | Date>
) {
  const maybeHas = (t as TranslateFn & {has?: (key: string) => boolean}).has
  if (typeof maybeHas === 'function' && !maybeHas(key)) {
    return fallback
  }

  try {
    return t(key, values)
  } catch {
    return fallback
  }
}

function formatDate(value: string | null | undefined, locale: string) {
  if (!value) return '-'
  const date = new Date(value.includes('T') ? value : `${value}T12:00:00`)
  if (Number.isNaN(date.getTime())) return value

  return new Intl.DateTimeFormat(locale, {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(date)
}

function formatDateTime(value: string | null | undefined, locale: string) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value

  return new Intl.DateTimeFormat(locale, {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date)
}

function formatTime(value?: string | null) {
  if (!value) return '-'
  const [hours = '0', minutes = '0'] = value.split(':')
  return `${hours}:${minutes}`
}

function todayKey() {
  return new Date().toLocaleDateString('en-CA')
}

function isOverdue(task: ExportableTask) {
  return task.status !== 'completed' && task.task_date < todayKey()
}

function safeFileName(value: string) {
  return value
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, '')
    .trim()
    .replace(/\s+/g, '-')
}

function applySheetDefaults(sheet: ExcelJS.Worksheet) {
  sheet.views = [{showGridLines: false}]
  sheet.properties.defaultRowHeight = 22

  sheet.columns?.forEach((column) => {
    column.alignment = {vertical: 'middle'}
  })
}

function setCell(
  sheet: ExcelJS.Worksheet,
  cell: string,
  value: string | number,
  options?: {
    bold?: boolean
    size?: number
    color?: string
    bg?: string
    align?: 'left' | 'center' | 'right'
  }
) {
  const current = sheet.getCell(cell)
  current.value = value
  current.font = {
    name: 'Aptos',
    size: options?.size ?? 11,
    bold: options?.bold ?? false,
    color: {argb: options?.color ?? COLORS.text},
  }

  current.alignment = {
    vertical: 'middle',
    horizontal: options?.align ?? 'left',
    wrapText: true,
  }

  if (options?.bg) {
    current.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: {argb: options.bg},
    }
  }
}

function styleTitle(
  sheet: ExcelJS.Worksheet,
  buildingName: string,
  locale: string,
  t: TranslateFn
) {
  sheet.mergeCells('B2:C3')
  setCell(sheet, 'B2', 'CONCIERGE\nAPP', {
    bold: true,
    size: 18,
    color: COLORS.green,
    align: 'center',
  })

  sheet.mergeCells('D2:I2')
  setCell(
    sheet,
    'D2',
    safeT(t, 'tasksExport.reportTitle', 'TASK REPORT'),
    {
      bold: true,
      size: 18,
      color: COLORS.greenDark,
    }
  )

  sheet.mergeCells('D3:I3')
  setCell(
    sheet,
    'D3',
    safeT(
      t,
      'tasksExport.reportSubtitle',
      `Operational summary for building ${buildingName}`,
      {buildingName}
    ),
    {
      size: 11,
      color: COLORS.text,
    }
  )

  setCell(
    sheet,
    'J2',
    safeT(t, 'tasksExport.generatedOn', 'Generated on:'),
    {size: 11, color: COLORS.text}
  )
  setCell(sheet, 'K2', formatDate(new Date().toISOString(), locale), {
    size: 11,
    color: COLORS.text,
  })

  setCell(sheet, 'J3', safeT(t, 'tasksExport.building', 'Building:'), {
    size: 11,
    color: COLORS.text,
  })
  setCell(
    sheet,
    'K3',
    buildingName || safeT(t, 'tasksExport.noBuilding', 'No building'),
    {
      size: 11,
      color: COLORS.text,
    }
  )

  setCell(sheet, 'J4', safeT(t, 'tasksExport.generatedBy', 'Generated by:'), {
    size: 11,
    color: COLORS.text,
  })
  setCell(sheet, 'K4', safeT(t, 'tasksExport.concierge', 'Concierge'), {
    size: 11,
    color: COLORS.text,
  })
}

function addMetricCard(
  sheet: ExcelJS.Worksheet,
  range: string,
  title: string,
  value: string | number,
  subtitle1: string,
  subtitle2: string,
  color: string,
  bg: string
) {
  sheet.mergeCells(range)

  const [start] = range.split(':')
  const cell = sheet.getCell(start)

  cell.value = {
    richText: [
      {
        text: `${title}\n`,
        font: {bold: true, size: 10, color: {argb: color}, name: 'Aptos'},
      },
      {
        text: `${value}\n`,
        font: {bold: true, size: 20, color: {argb: color}, name: 'Aptos'},
      },
      {
        text: `${subtitle1}\n${subtitle2}`,
        font: {size: 10, color: {argb: COLORS.text}, name: 'Aptos'},
      },
    ],
  }

  cell.alignment = {
    vertical: 'middle',
    horizontal: 'left',
    wrapText: true,
  }

  cell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: {argb: bg},
  }

  cell.border = {
    top: {style: 'thin', color: {argb: COLORS.border}},
    left: {style: 'thin', color: {argb: COLORS.border}},
    bottom: {style: 'thin', color: {argb: COLORS.border}},
    right: {style: 'thin', color: {argb: COLORS.border}},
  }
}

function addSectionTitle(sheet: ExcelJS.Worksheet, row: number, title: string) {
  sheet.mergeCells(`B${row}:K${row}`)
  setCell(sheet, `B${row}`, title, {
    bold: true,
    size: 13,
    color: COLORS.greenDark,
  })
}

function styleHeader(row: ExcelJS.Row) {
  row.eachCell((cell) => {
    cell.font = {
      name: 'Aptos',
      size: 10,
      bold: true,
      color: {argb: COLORS.white},
    }
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: {argb: COLORS.greenDark},
    }
    cell.alignment = {
      vertical: 'middle',
      horizontal: 'center',
      wrapText: true,
    }
    cell.border = {
      top: {style: 'thin', color: {argb: COLORS.greenDark}},
      left: {style: 'thin', color: {argb: COLORS.greenDark}},
      bottom: {style: 'thin', color: {argb: COLORS.greenDark}},
      right: {style: 'thin', color: {argb: COLORS.greenDark}},
    }
  })
}

function styleTableBody(sheet: ExcelJS.Worksheet, startRow: number, endRow: number) {
  for (let rowNumber = startRow; rowNumber <= endRow; rowNumber += 1) {
    const row = sheet.getRow(rowNumber)

    row.eachCell((cell) => {
      cell.font = {
        name: 'Aptos',
        size: 10,
        color: {argb: COLORS.text},
      }
      cell.alignment = {
        vertical: 'middle',
        wrapText: true,
      }
      cell.border = {
        top: {style: 'thin', color: {argb: COLORS.border}},
        left: {style: 'thin', color: {argb: COLORS.border}},
        bottom: {style: 'thin', color: {argb: COLORS.border}},
        right: {style: 'thin', color: {argb: COLORS.border}},
      }
    })

    if (rowNumber % 2 === 0) {
      row.eachCell((cell) => {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: {argb: 'FAFCFF'},
        }
      })
    }
  }
}

function translateCategory(category: string | null | undefined, t: TranslateFn) {
  if (!category) return '-'

  return safeT(
    t,
    `taskLabels.${getCategoryKey(category as EditableTask['category'])}`,
    category
  )
}

function translatePriority(priority: string | null | undefined, t: TranslateFn) {
  if (!priority) return '-'

  return safeT(
    t,
    `taskLabels.${getPriorityKey(priority as EditableTask['priority'])}`,
    priority
  )
}

function translateStatus(status: string | null | undefined, t: TranslateFn) {
  if (!status) return '-'

  return safeT(
    t,
    `taskLabels.${getStatusKey(status as EditableTask['status'])}`,
    status
  )
}

function buildSummaryByCategory(tasks: ExportableTask[], t: TranslateFn) {
  const map = new Map<
    string,
    {
      category: string
      total: number
      completed: number
      pending: number
      overdue: number
      urgent: number
    }
  >()

  tasks.forEach((task) => {
    const key = task.category || 'other'

    if (!map.has(key)) {
      map.set(key, {
        category: translateCategory(key, t),
        total: 0,
        completed: 0,
        pending: 0,
        overdue: 0,
        urgent: 0,
      })
    }

    const row = map.get(key)
    if (!row) return

    row.total += 1
    if (task.status === 'completed') row.completed += 1
    else row.pending += 1
    if (isOverdue(task)) row.overdue += 1
    if (task.priority === 'high' && task.status !== 'completed') row.urgent += 1
  })

  return Array.from(map.values()).sort((a, b) => a.category.localeCompare(b.category))
}

function addSummaryTable(sheet: ExcelJS.Worksheet, tasks: ExportableTask[], t: TranslateFn) {
  const rows = buildSummaryByCategory(tasks, t)
  const startRow = 12

  addSectionTitle(
    sheet,
    11,
    safeT(t, 'tasksExport.sections.summaryByCategory', '1. TASK SUMMARY BY CATEGORY')
  )

  sheet.getRow(startRow).values = [
    '',
    safeT(t, 'tasksExport.summaryColumns.category', 'Category'),
    safeT(t, 'tasksExport.summaryColumns.totalAssigned', 'Total assigned'),
    safeT(t, 'tasksExport.summaryColumns.completed', 'Completed'),
    safeT(t, 'tasksExport.summaryColumns.pending', 'Pending'),
    safeT(t, 'tasksExport.summaryColumns.overdue', 'Overdue'),
    safeT(t, 'tasksExport.summaryColumns.urgent', 'Urgent'),
    safeT(t, 'tasksExport.summaryColumns.percentCompleted', '% completed'),
  ]

  styleHeader(sheet.getRow(startRow))

  rows.forEach((item, index) => {
    const row = sheet.getRow(startRow + 1 + index)
    const percent = item.total > 0 ? Math.round((item.completed / item.total) * 100) : 0

    row.values = [
      '',
      item.category,
      item.total,
      item.completed,
      item.pending,
      item.overdue,
      item.urgent,
      `${percent}%`,
    ]
  })

  const totalRow = sheet.getRow(startRow + 1 + rows.length)
  const total = rows.reduce((sum, row) => sum + row.total, 0)
  const completed = rows.reduce((sum, row) => sum + row.completed, 0)

  totalRow.values = [
    '',
    safeT(t, 'tasksExport.totalRow', 'TOTAL'),
    total,
    completed,
    rows.reduce((sum, row) => sum + row.pending, 0),
    rows.reduce((sum, row) => sum + row.overdue, 0),
    rows.reduce((sum, row) => sum + row.urgent, 0),
    total > 0 ? `${Math.round((completed / total) * 100)}%` : '0%',
  ]

  styleTableBody(sheet, startRow + 1, startRow + 1 + rows.length)

  totalRow.eachCell((cell) => {
    cell.font = {name: 'Aptos', bold: true, size: 10, color: {argb: COLORS.text}}
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: {argb: COLORS.greenLight},
    }
  })
}

function addDetailedTasksTable(
  sheet: ExcelJS.Worksheet,
  tasks: ExportableTask[],
  latestPendingReasonMap: Map<string, string>,
  locale: string,
  t: TranslateFn
) {
  const startRow = 23

  addSectionTitle(
    sheet,
    22,
    safeT(t, 'tasksExport.sections.taskDetails', '2. TASK DETAILS')
  )

  sheet.getRow(startRow).values = [
    '',
    safeT(t, 'tasksExport.detailColumns.createdAt', 'Created at'),
    safeT(t, 'tasksExport.detailColumns.taskDate', 'Task date'),
    safeT(t, 'tasksExport.detailColumns.time', 'Time'),
    safeT(t, 'tasksExport.detailColumns.title', 'Title'),
    safeT(t, 'tasksExport.detailColumns.location', 'Location'),
    safeT(t, 'tasksExport.detailColumns.category', 'Category'),
    safeT(t, 'tasksExport.detailColumns.priority', 'Priority'),
    safeT(t, 'tasksExport.detailColumns.status', 'Status'),
    safeT(t, 'tasksExport.detailColumns.completedAt', 'Completed at'),
    safeT(
      t,
      'tasksExport.detailColumns.reasonReturnedPending',
      'Reason returned to pending'
    ),
    safeT(t, 'tasksExport.detailColumns.notes', 'Notes'),
  ]

  styleHeader(sheet.getRow(startRow))

  tasks.forEach((task, index) => {
    const row = sheet.getRow(startRow + 1 + index)

    row.values = [
      '',
      formatDateTime(task.created_at, locale),
      formatDate(task.task_date, locale),
      formatTime(task.task_time),
      task.title,
      task.apartment_or_area || '-',
      translateCategory(task.category, t),
      translatePriority(task.priority, t),
      translateStatus(task.status, t),
      formatDateTime(task.completed_at, locale),
      latestPendingReasonMap.get(task.id) || '-',
      task.description || '-',
    ]
  })

  styleTableBody(sheet, startRow + 1, startRow + tasks.length)
  sheet.autoFilter = {
    from: `B${startRow}`,
    to: `L${startRow + tasks.length}`,
  }
}

function setupColumns(sheet: ExcelJS.Worksheet) {
  sheet.columns = [
    {width: 3},
    {width: 20},
    {width: 16},
    {width: 10},
    {width: 34},
    {width: 18},
    {width: 16},
    {width: 13},
    {width: 15},
    {width: 20},
    {width: 28},
    {width: 42},
  ]
}

function createDetailsSheet(
  workbook: ExcelJS.Workbook,
  name: string,
  tasks: ExportableTask[],
  latestPendingReasonMap: Map<string, string>,
  locale: string,
  t: TranslateFn
) {
  const sheet = workbook.addWorksheet(name)
  applySheetDefaults(sheet)

  sheet.columns = [
    {width: 16},
    {width: 34},
    {width: 18},
    {width: 16},
    {width: 13},
    {width: 15},
    {width: 20},
    {width: 28},
    {width: 42},
  ]

  sheet.getRow(1).values = [
    safeT(t, 'tasksExport.detailColumns.taskDate', 'Task date'),
    safeT(t, 'tasksExport.detailColumns.title', 'Title'),
    safeT(t, 'tasksExport.detailColumns.location', 'Location'),
    safeT(t, 'tasksExport.detailColumns.category', 'Category'),
    safeT(t, 'tasksExport.detailColumns.priority', 'Priority'),
    safeT(t, 'tasksExport.detailColumns.status', 'Status'),
    safeT(t, 'tasksExport.detailColumns.completedAt', 'Completed at'),
    safeT(
      t,
      'tasksExport.detailColumns.reasonReturnedPending',
      'Reason returned to pending'
    ),
    safeT(t, 'tasksExport.detailColumns.notes', 'Notes'),
  ]

  styleHeader(sheet.getRow(1))

  tasks.forEach((task, index) => {
    sheet.getRow(index + 2).values = [
      formatDate(task.task_date, locale),
      task.title,
      task.apartment_or_area || '-',
      translateCategory(task.category, t),
      translatePriority(task.priority, t),
      translateStatus(task.status, t),
      formatDateTime(task.completed_at, locale),
      latestPendingReasonMap.get(task.id) || '-',
      task.description || '-',
    ]
  })

  if (tasks.length > 0) {
    styleTableBody(sheet, 2, tasks.length + 1)
  }

  sheet.autoFilter = {
    from: 'A1',
    to: `I${tasks.length + 1}`,
  }

  return sheet
}

function createStatusHistorySheet(
  workbook: ExcelJS.Workbook,
  history: TaskStatusHistoryEntry[],
  taskMap: Map<string, ExportableTask>,
  locale: string,
  t: TranslateFn
) {
  const sheet = workbook.addWorksheet(
    safeT(t, 'tasksExport.sheets.statusHistory', 'Status history')
  )
  applySheetDefaults(sheet)

  sheet.columns = [
    {width: 22},
    {width: 32},
    {width: 16},
    {width: 16},
    {width: 40},
  ]

  sheet.getRow(1).values = [
    safeT(t, 'tasksExport.historyColumns.date', 'Date'),
    safeT(t, 'tasksExport.historyColumns.task', 'Task'),
    safeT(t, 'tasksExport.historyColumns.previousStatus', 'Previous status'),
    safeT(t, 'tasksExport.historyColumns.newStatus', 'New status'),
    safeT(t, 'tasksExport.historyColumns.reason', 'Reason'),
  ]

  styleHeader(sheet.getRow(1))

  history.forEach((entry, index) => {
    const task = taskMap.get(entry.task_id)

    sheet.getRow(index + 2).values = [
      formatDateTime(entry.created_at, locale),
      task?.title || entry.task_id,
      translateStatus(entry.from_status, t),
      translateStatus(entry.to_status, t),
      entry.reason || '-',
    ]
  })

  if (history.length > 0) {
    styleTableBody(sheet, 2, history.length + 1)
  } else {
    sheet.getRow(2).values = [
      safeT(t, 'tasksExport.noStatusHistory', 'No status changes recorded yet.'),
      '',
      '',
      '',
      '',
    ]
    styleTableBody(sheet, 2, 2)
  }

  sheet.autoFilter = {
    from: 'A1',
    to: `E${history.length + 1}`,
  }
}

export async function exportTasksToExcel({
  tasks,
  buildingName,
  locale,
  t,
}: ExportTasksToExcelParams) {
  if (!tasks.length) return

  const statusHistory = await fetchTaskStatusHistory(tasks.map((task) => task.id))
  const latestPendingReasonMap = buildLatestPendingReasonMap(statusHistory)
  const taskMap = new Map(tasks.map((task) => [task.id, task] as const))

  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'Concierge App'
  workbook.created = new Date()

  const completedCount = tasks.filter((task) => task.status === 'completed').length
  const pendingCount = tasks.filter((task) => task.status !== 'completed').length
  const overdueCount = tasks.filter((task) => isOverdue(task)).length
  const urgentCount = tasks.filter(
    (task) => task.priority === 'high' && task.status !== 'completed'
  ).length
  const completedPercent =
    tasks.length > 0 ? Math.round((completedCount / tasks.length) * 100) : 0

  const sheet = workbook.addWorksheet(
    safeT(t, 'tasksExport.sheets.summary', 'General summary')
  )
  setupColumns(sheet)
  applySheetDefaults(sheet)

  styleTitle(sheet, buildingName, locale, t)

  addMetricCard(
    sheet,
    'B6:C8',
    safeT(t, 'tasksExport.metrics.completedPercentTitle', '% TASKS COMPLETED'),
    `${completedPercent}%`,
    safeT(t, 'tasksExport.metrics.completedPercentLine1', 'Completed total: {count}', {
      count: completedCount,
    }),
    safeT(t, 'tasksExport.metrics.completedPercentLine2', 'Assigned total: {count}', {
      count: tasks.length,
    }),
    COLORS.green,
    'F8FCFA'
  )

  addMetricCard(
    sheet,
    'D6:E8',
    safeT(t, 'tasksExport.metrics.pendingTitle', 'PENDING TASKS'),
    pendingCount,
    safeT(t, 'tasksExport.metrics.pendingLine1', 'Pending: {count}', {
      count: pendingCount,
    }),
    safeT(t, 'tasksExport.metrics.pendingLine2', 'In this report'),
    COLORS.blue,
    COLORS.blueLight
  )

  addMetricCard(
    sheet,
    'F6:G8',
    safeT(t, 'tasksExport.metrics.overdueTitle', 'OVERDUE TASKS'),
    overdueCount,
    safeT(t, 'tasksExport.metrics.overdueLine1', 'Overdue total: {count}', {
      count: overdueCount,
    }),
    safeT(t, 'tasksExport.metrics.overdueLine2', 'Need attention'),
    COLORS.red,
    COLORS.redLight
  )

  addMetricCard(
    sheet,
    'H6:I8',
    safeT(t, 'tasksExport.metrics.urgentTitle', 'URGENT'),
    urgentCount,
    safeT(t, 'tasksExport.metrics.urgentLine1', 'High priority: {count}', {
      count: urgentCount,
    }),
    safeT(t, 'tasksExport.metrics.urgentLine2', 'Not completed'),
    COLORS.amber,
    COLORS.amberLight
  )

  addSummaryTable(sheet, tasks, t)
  addDetailedTasksTable(sheet, tasks, latestPendingReasonMap, locale, t)

  createDetailsSheet(
    workbook,
    safeT(t, 'tasksExport.sheets.completed', 'Completed'),
    tasks.filter((task) => task.status === 'completed'),
    latestPendingReasonMap,
    locale,
    t
  )

  createDetailsSheet(
    workbook,
    safeT(t, 'tasksExport.sheets.overdue', 'Overdue'),
    tasks.filter((task) => isOverdue(task)),
    latestPendingReasonMap,
    locale,
    t
  )

  createDetailsSheet(
    workbook,
    safeT(t, 'tasksExport.sheets.urgent', 'Urgent'),
    tasks.filter((task) => task.priority === 'high' && task.status !== 'completed'),
    latestPendingReasonMap,
    locale,
    t
  )

  createStatusHistorySheet(workbook, statusHistory, taskMap, locale, t)

  const buffer = await workbook.xlsx.writeBuffer()

  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })

  const date = new Date().toISOString().split('T')[0]
  const safeBuildingName = safeFileName(
    buildingName || safeT(t, 'tasksExport.noBuilding', 'building')
  )
  const filePrefix = safeFileName(safeT(t, 'tasksExport.filePrefix', 'tasks'))

  saveAs(blob, `${filePrefix}-${safeBuildingName}-${date}.xlsx`)
}
